// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psnzzbwobxmiuhaekhyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbnp6YndvYnhtaXVoYWVraHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDI1NjYsImV4cCI6MjA1ODk3ODU2Nn0.Vys4k8zjgFqx-mrTgEuLNblCx_Q0Onx0Lst5xofgAZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});